// Onboarding questionnaire configuration
const ONBOARDING_QUESTIONS = [
  {
    id: 1,
    type: "singleChoice",
    text: "Let's start simple",
    questionText: "What should I call you?",
  },
  {
    id: 2,
    type: "multipleChoice",
    text: "Initial Assessment",
    questionText:
      "Let's understand your business better: what's your industry?",
    options: [
      { description: "Professional Services" },
      { description: "Healthcare" },
      { description: "Retail" },
      { description: "Construction" },
      { description: "Manufacturing" },
      { description: "Technology" },
      { description: "Hospitality" },
      { description: "Other" },
    ],
  },
  {
    id: 3,
    type: "multipleChoice",
    text: "Business Activity",
    questionText: "What's your current business status?",
    subText: "Where are you in your business journey?",
    options: [
      { description: "Just Starting" },
      { description: "Established Business" },
      { description: "Growing Business" },
      { description: "Scaling Business" },
      { description: "Mature Business" },
      { description: "Other" },
    ],
  },
  {
    id: 4,
    type: "multipleChoice",
    text: "Business Health Check",
    questionText: "What are your current business challenges?",
    options: [
      { description: "Ahh... people issues" },
      { description: "I don't earn enough" },
      { description: "Not enough leads are coming into my business" },
      { description: "Cash flow is a nightmare" },
      { description: "What am I doing? Where do I go?" },
      { description: "None of the above" },
      { description: "All of the above" },
    ],
  },
  {
    id: 5,
    type: "multipleChoice",
    text: "Goals Selection",
    questionText: "What's your main goal?",
    options: [
      { description: "Grow at a steady rate" },
      { description: "Have a lean, mean fighting machine" },
      { description: "Build a team of high performers" },
      { description: "We have a great customer base, let's keep them" },
      { description: "Just make business easier" },
      { description: "Increase the value of my business" },
      { description: "Take over the world" },
      { description: "Give me the life I want" },
      { description: "Disrupt, disrupt, disrupt" },
    ],
  },
  {
    id: 6,
    type: "multipleChoice",
    text: "What if",
    questionText:
      "Imagine I have a magic wand, where will we be together in 10 years?",
    options: [
      { description: "On a beach" },
      { description: "In a fast car and with a yacht" },
      { description: "Invested and set up for life" },
      { description: "Still building the empire" },
      { description: "Volunteering my time" },
      { description: "Retired" },
      { description: "Beating the door down continuing to grow" },
      { description: "Mentoring and sitting on a board or two" },
    ],
  },
  {
    id: 7,
    type: "multipleChoice",
    text: "Select Your Priorities",
    questionText:
      "As your super-powered business partner, if we were to focus our attention on something, what would it be?",
    options: [
      { description: "Startup Guidance" },
      { description: "Rapid Turnaround" },
      { description: "Breaking through to the next level" },
      { description: "Digital Transformation" },
      { description: "Strategy and Planning" },
      { description: "Financial Planning and Management" },
      { description: "Marketing Strategy" },
      { description: "Team Management" },
    ],
  },
  {
    id: 8,
    type: "multipleChoice",
    text: "Your typical Workday",
    questionText: "What's your typical business day like?",
    options: [
      { description: "Mostly working from home" },
      { description: "Physical store — on the floor" },
      { description: "Hybrid Business Model" },
      { description: "Service-based business" },
      { description: "Managing multiple locations with a HQ" },
      { description: "Warehouse and/or we make stuff" },
      { description: "On the road and on the tools" },
    ],
  },
  {
    id: 9,
    type: "multipleChoice",
    text: "Targets",
    questionText: "What's your revenue target?",
    options: [
      { description: "Less than $10,000" },
      { description: "$10,000 – $100,000" },
      { description: "$100,000 – $500,000" },
      { description: "$500,000 – $1M" },
      { description: "$1M+" },
      { description: "$5M+" },
      { description: "$10M+" },
    ],
  },
  {
    id: 10,
    type: "multipleChoice",
    text: "Targets",
    questionText: "How much money do you want in your pocket?",
    options: [
      { description: "Less than $10,000" },
      { description: "$10,000 – $100,000" },
      { description: "$100,000 – $500,000" },
      { description: "$500,000 – $1M" },
      { description: "$1M+" },
      { description: "$5M+" },
      { description: "$10M+" },
    ],
  },
];

export default ONBOARDING_QUESTIONS;
